pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                snykSecurity additionalArguments: 'foo', failOnIssues: false, snykInstallation: 'personalSnyk', snykTokenId: 'snykPersonalToken'
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
